### ISSUE TITLE
Sensor init procedure hangs.

### ISSUE THREAD

**Issue by ChristianDLRR** [pimoroni/icp10125-python#2]
Dear support team,
I tested the ICP10125 breakout with PicoPi.
To test it I used the example I found here:
https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/examples/breakout_icp10125/normal_demo.py

This is the code:

import time
import breakout_icp10125
import pimoroni_i2c
i2c = pimoroni_i2c.PimoroniI2C(4, 5)
icp10125 = breakout_icp10125.BreakoutICP10125(i2c)
while True:
    t, p, status = icp10125.measure(icp10125.NORMAL)
    if status == icp10125.STATUS_OK:
        print(t, p)
    time.sleep(1.0)

I'm using the breakout garden pack connected to the Pico Decker Quad Expander. So no wires, I just plugged in the PicoPi and the breakout board.
The firmware is "MicroPython v1.18 on 2022-01-27; Raspberry Pi Pico with RP2040" and I'm using Thonny to run the code.
Apparently the execution got stuck to this line:

icp10125 = breakout_icp10125.BreakoutICP10125(i2c)

I do not think it is  an HW issue of the breakboard because I tested it with Arduino and it works fine.
So, I think it is a SW issue of the library.

Kind regards.
Christian.

**Comment by Gadgetoid** [comment]
This is on my list to look into today. I think I came across this same hang, but it seemed to go away after some tinkering so I didn't think anything of it.

IIRC this hang also happened with the sensor unplugged. Have you tried- for the elimination of doubt- connecting the Breakout Garden Pack directly to the Pico?

**Comment by Gadgetoid** [comment]
After some looking into this, there's definitely something going awry.

For posterity rather than as a direct answer to your issue, it looks like the Pico SDK's  `i2c_write_blocking_internal` is failing to handle a repeated start condition indicated by checking: `I2C_IC_RAW_INTR_STAT_START_DET_BITS`

It basically gets to:

```c++
                do {
                    if (timeout_check) {
                        timeout = timeout_check(ts);
                        abort |= timeout;
                    }
                    tight_loop_contents();
                } while (!timeout && !(i2c->hw->raw_intr_stat & I2C_IC_RAW_INTR_STAT_STOP_DET_BITS));
```

And sits in an infinite loop, because it's checking for a *stop* condition after the transaction has finished, but not a *repeated start*.

**Comment by Gadgetoid** [comment]
Okay everything I just said was nonsense, it was a bug hiding in our driver.

Try this version of MicroPython and see if it works for you - https://github.com/pimoroni/pimoroni-pico/suites/5249803331/artifacts/161729785

**Comment by Gadgetoid** [comment]
Should be fixed in - https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.18.1

**Comment by ChristianDLRR** [comment]
I confirm that it is fixed now.

Thank you.
Regards,
Christian.

Il giorno gio 10 feb 2022 alle ore 19:17 Philip Howard <
***@***.***> ha scritto:
